default: &default
  adapter: <%= ENV['DEV_DATABASE_ADAPTER'] %>
  encoding: <%= ENV['DEV_DATABASE_ENCODING'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  host: <%= ENV['DEV_DATABASE_HOST'] %>
  port: <%= ENV['DEV_DATABASE_PORT'] %>
  database: <%= ENV['DEV_DATABASE'] %>
  username: <%= ENV['DEV_DATABASE_USER'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>

test:
  <<: *development
  database: <%= ENV['DEV_DATABASE_TEST'] %>

production:
  <<: *default
  database: conexaog20_production
  username: <%= ENV['CONEXAOG20_DATABASE_USER'] %>
  password: <%= ENV['CONEXAOG20_DATABASE_PASSWORD'] %>
